name: Python test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  security-events: write
  contents: read

jobs:
  # Google OSV-Scanner
  scan-pr:
    uses: "geoderp/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v0.0.1"
    with:
      scan-args: |-
        --recursive
        ./
    permissions:
      security-events: write
      contents: read
      actions: read
  build:
    runs-on: ${{ matrix.os }}
    needs:
      - scan-pr
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install
        with:
          python-version-file: ".python-version"

      - name: Special dependencies for macos
        run: |
          brew install hdf5
          uv pip install numpy==1.26.0
          uv pip install tables==3.9.1
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Install EMHASS with test dependencies
        run: |
          uv pip install .[test]

      - name: Test with pytest
        run: |
           uv run pytest
