name: Python test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  security-events: write
  contents: read

jobs:
  # Google OSV-Scanner
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Set up Python venv
        run: uv venv && source .venv/bin/activate
      - name: Special dependencies for macos
        run: |
          source .venv/bin/activate
          brew install hdf5
          uv pip install numpy==2.0.0
          uv pip install tables==3.10.2
          uv pip install pulp==3.2.0
          uv run pulptest
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install EMHASS with test dependencies
        run: |
          source .venv/bin/activate && uv sync --reinstall --extra test
      - name: Test with pytest
        run: |
          source .venv/bin/activate uv run pytest
  scan-pr:
    needs:
      - build
    uses: "geoderp/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v0.0.1"
    with:
      fail-on-vuln: false
      scan-args: |-
        --recursive
        ./
    permissions:
      security-events: write
      contents: read
      actions: read