name: update EMHASS inverter and module PVLib database

on:
  push:
    branches: [ master ]
  schedule: # run once a month
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:
  pull-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: install requirements
      run: python3 -m pip install --break-system-packages .[test]
    - name: pull latest SAM CEC files
      run: |
        git pull https://github.com/NREL/SAM.git 
        cp "./SAM/tree/develop/deploy/libraries/CEC Inverters.csv" ./src/emhass/data/CEC Inverters.csv
        cp "./SAM/tree/develop/deploy/libraries/CEC Modules.csv" ./src/emhass/data/CEC Modules.csv
    - name: build database via python script
      run: python3 ./scripts/save_pvlib_module_inverter_database.py
    - name: push changes
      run: |
        git config --global user.name "PVLib_Updater"
        git config --global user.email "18461782+GeoDerp@users.noreply.github.com
        git add ./src/emhass/data/cec_inverters.pbz2
        git add ./src/emhass/data/Modules.pbz2
        git commit -m "Bump inverter/module database"
        git push